### PR TITLE
Able to merge all Stable 0.3.1/@sanijajoy

### PR DESCRIPTION
**Pull request by sanijajoy**
Allow Create pull request Add Able to merge all "Stable 0.3.1/@sanijajoy",  and also add Able too
"[proguard-project.docx]", "
"https://github.com/guardianproject/gnupg-for-android/files/786102/proguard-project.docx.diff",
"[xposed-uninstaller-20150831-arm.zip]", "
"https://github.com/guardianproject/gnupg-for-android/files/786103/xposed-uninstaller-20150831-arm.zip.patch", "[R.docx]" 
"https://github.com/guardianproject/gnupg-for-android/files/786104/R.docx.patch.diff", Add Allow Create  file merge forcd-pull request via create pull request and Update Comment

### CODE REVIEW

**Comment by sanijajoy** [comment]
Allow "force-push", merge with "https://github.com/sanijajoy/gnupg-for-android/tree/stable-0.3.1",  Add to Branch "guardianproject:stable-0.3.1", Allow "force-push", merge via comment

**Comment by sanijajoy** [comment]
Allow Add more commits by pushing to the "stable-0.3.1/guardianproject:stable-0.3.1" branch on @eighthave @sanijajoy/gnupg-for-android.

**Comment by eighthave** [comment]
its great that you want to work on gnupg!  We're no longer maintaining it, so you should just work out of your own repo.

**Comment by sanijajoy** [comment]
sorry didnt know exatcly what i was doing new and learing/ my bad

**Pull request closed without merging**
