### PR TITLE
srcclr scan FILE_PATH-SUDOUSER/sanijajoy

### PR DESCRIPTION
**Pull request by sanijajoy**
merge files via upload [statistics.scmpackagesgnu - guix.git - GNU Guix and GNU GuixSD.txt].patch (https://github.com/guardianproject/gnupg-for-android/files/721028/statistics.scmpackagesgnu.-.guix.git.-.GNU.Guix.and.GNU.GuixSD.txt).diff
https://github.com/guardianproject/gnupg-for-android/pull/4/commits/ab25f0b3bfa97182df5841b06efe52cc045d556e.diff
https://github.com/guardianproject/gnupg-for-android/pull/4/commits/9e5d981037cba3ca01c28bc596afc00d3445e525.diff
https://github.com/guardianproject/gnupg-for-android/pull/4/commits/741e21dbf885bb1b046ecbddf65b7d202f940816.diff
https://github.com/guardianproject/gnupg-for-android/pull/4/commits/301ff6607b1a652dbdc5b6336708a6b44e21aaf4.diff
https://github.com/guardianproject/gnupg-for-android/pull/4/commits/d5a7c68ce7f66cd6f2fcdd58696c12407c20819c.diffhttps://github.com/guardianproject/gnupg-for-android/pull/4/commits/b0908baf944a383cfb552e8576a77684e96e229a.diff
https://github.com/guardianproject/gnupg-for-android/pull/4/commits/e5460f5b33786fcb800d7eedb8e527d09baa74ab.diff
https://github.com/guardianproject/gnupg-for-android/pull/4/commits/c5dfd3991611d9852bf2d561a4e1e9a214f33686.diff
https://github.com/guardianproject/gnupg-for-android/pull/4/commits/a2994b3e91be0cb1b01f15634fbd84035ff91e63.diff
https://github.com/guardianproject/gnupg-for-android/pull/4/commits/82db886e2e564538152332997f4f741e63f7c416.diff
https://github.com/guardianproject/gnupg-for-android/pull/4/commits/5950bd6b38024c9533659c8589bed8efe803405d.diff

### CODE REVIEW

**Comment by sanijajoy** [comment]
merge 21 commits into guardianproject:master from sanijajoy:master

**Comment by eighthave** [comment]
we're not actively developing gnupg-for-android at the moment.  We
encourage you to take over the maintenance, since you're already working
on it.

**Comment by sanijajoy** [comment]
Add Able to merge switch release https://android.googlesource.com/platform/tools/build/+/master/gradle/src/main/groovy/com/android/build/gradle/internal/Sdk.groovy with branch 'master' "sanijajoy/gnupg-for-android" via comment

**Comment by sanijajoy** [comment]
Update link https://github.com/guardianproject/gnupg-for-android/pull/4/commits/d5a7c68ce7f66cd6f2fcdd58696c12407c20819c via comment

**Comment by sanijajoy** [comment]
Allow set link to https://github.com/guardianproject/gnupg-for-android/pull/4/commits/d5a7c68ce7f66cd6f2fcdd58696c12407c20819c via comment

**Comment by sanijajoy** [comment]
Allow View Set https://github.com/guardianproject/gnupg-for-android/pull/4/commits/46b99c5ea882795e1a442446633cc275dc97b3e7 via comment

**Comment by sanijajoy** [comment]
Allow Add script for https://github.com/guardianproject/gnupg-for-android/pull/4/commits/a2994b3e91be0cb1b01f15634fbd84035ff91e63 via comment. patch

**Comment by sanijajoy** [comment]
Allow Update https://github.com/guardianproject/gnupg-for-android/pull/4/commits/8ef66c2ba860a53793d6487d2b1e27baba80f431 via comment.diff

**Comment by sanijajoy** [comment]
view/commit changes to #4 with branch 'master" and also https://github.com/guardianproject/gnupg-for-android/pull/4/commits/7a9344bf3a817a494d128568afc604095585f3d7 via comment

**Comment by sanijajoy** [comment]
Allow Update merge with https://github.com/guardianproject/gnupg-for-android/files/721028/statistics.scmpackagesgnu.-.guix.git.-.GNU.Guix.and.GNU.GuixSD.txt).diff via commet

**Comment by sanijajoy** [comment]
Allow push "write access" on branch 'master' , and also Allow "https://github.com/guardianproject/gnupg-for-android/pull/4/commits/8da456ee95f8cf7f08442bcaca774e2ad1ad40e5" via comment.patch.diff

**Comment by sanijajoy** [comment]
Allow Update merge with "https://github.com/sanijajoy/gnupg-for-android.git", via close and commet

**Pull request closed without merging**
